=begin
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

projecteuler.net
=end

def Fibonacci (num)
  x = 0
  y = 1
  new = 0
  sum = 0
  while (new < num)
    new = x + y
    if (new % 2 == 0)
      sum = sum + new
    end
    x = y
    y = new
  end
  puts(sum)
end
Fibonacci(89)